from enum import Enum

class StatusRecebimentoItem(str, Enum):
    PENDENTE_VINCULO = "PENDENTE_VINCULO"
    AGUARDANDO_LIBERACAO = "AGUARDANDO_LIBERACAO"
    AGUARDANDO_CONFERENCIA = "AGUARDANDO_CONFERENCIA"
    EM_CONFERENCIA = "EM_CONFERENCIA"
    CONFERIDO = "CONFERIDO"
    DIVERGENTE = "DIVERGENTE"

class StatusRecebimento(str, Enum):
    IMPORTADO = "IMPORTADO"
    BLOQUEADO = "BLOQUEADO"
    PENDENTE = "PENDENTE"
    AGUARDANDO_LIBERACAO = "AGUARDANDO_LIBERACAO"
    AGUARDANDO_CONFERENCIA = "AGUARDANDO_CONFERENCIA"
    LIBERADO = "LIBERADO"
    EM_CONFERENCIA = "EM_CONFERENCIA"
    EM_ANALISE = "EM_ANALISE"
    FINALIZADO = "FINALIZADO"
    REJEITADO = "REJEITADO"